### ISSUE TITLE
AttributeError: 'X509' object has no attribute '_x509' in /script.module.requests/lib/requests/packages/urllib3/contrib/pyopenssl.py

### ISSUE THREAD

**Issue by greve** [Freso/script.module.requests#15]
I'm having issues with this in Kodi 17.1:

>   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
>                                              - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
>                                             Error Type: <type 'exceptions.AttributeError'>
>                                             Error Contents: 'X509' object has no attribute '_x509'
>                                             Traceback (most recent call last):
>                                               File "/home/guest/.kodi/addons/plugin.video.youtube/default.py", line 7, in <module>
>                                                 runner.run(__provider__)
>                                               File "/home/guest/.kodi/addons/plugin.video.youtube/resources/lib/kodion/runner.py", line 32, in run
>                                                 __RUNNER__.run(provider, context)
>                                               File "/home/guest/.kodi/addons/plugin.video.youtube/resources/lib/kodion/impl/xbmc/xbmc_runner.py", line 23, in run
>                                                 results = provider.navigate(context)
>                                               File "/home/guest/.kodi/addons/plugin.video.youtube/resources/lib/kodion/abstract_provider.py", line 93, in navigate
>                                                 result = method(context, re_match)
>                                               File "/home/guest/.kodi/addons/plugin.video.youtube/resources/lib/kodion/register_provider_path.py", line 12, in wrapper
>                                                 return func(*args, **kwargs)
>                                               File "/home/guest/.kodi/addons/plugin.video.youtube/resources/lib/youtube/provider.py", line 431, in _on_sign
>                                                 yt_login.process(mode, self, context, re_match, context.get_settings().requires_dual_login())
>                                               File "/home/guest/.kodi/addons/plugin.video.youtube/resources/lib/youtube/helper/yt_login.py", line 93, in process
>                                                 access_token_tv, expires_in_tv, refresh_token_tv = _do_login(_for_tv=True)
>                                               File "/home/guest/.kodi/addons/plugin.video.youtube/resources/lib/youtube/helper/yt_login.py", line 11, in _do_login
>                                                 json_data = _client.generate_user_code_tv()
>                                               File "/home/guest/.kodi/addons/plugin.video.youtube/resources/lib/youtube/client/login_client.py", line 187, in generate_user_code_tv
>                                                 return self.generate_user_code(client_id=client_id)
>                                               File "/home/guest/.kodi/addons/plugin.video.youtube/resources/lib/youtube/client/login_client.py", line 211, in generate_user_code
>                                                 result = requests.post(url, data=post_data, headers=headers, verify=self._verify)
>                                               File "/home/guest/.kodi/addons/script.module.requests/lib/requests/api.py", line 110, in post
>                                                 return request('post', url, data=data, json=json, **kwargs)
>                                               File "/home/guest/.kodi/addons/script.module.requests/lib/requests/api.py", line 56, in request
>                                                 return session.request(method=method, url=url, **kwargs)
>                                               File "/home/guest/.kodi/addons/script.module.requests/lib/requests/sessions.py", line 488, in request
>                                                 resp = self.send(prep, **send_kwargs)
>                                               File "/home/guest/.kodi/addons/script.module.requests/lib/requests/sessions.py", line 609, in send
>                                                 r = adapter.send(request, **kwargs)
>                                               File "/home/guest/.kodi/addons/script.module.requests/lib/requests/adapters.py", line 423, in send
>                                                 timeout=timeout
>                                               File "/home/guest/.kodi/addons/script.module.requests/lib/requests/packages/urllib3/connectionpool.py", line 594, in urlopen
>                                                 chunked=chunked)
>                                               File "/home/guest/.kodi/addons/script.module.requests/lib/requests/packages/urllib3/connectionpool.py", line 350, in _make_request
>                                                 self._validate_conn(conn)
>                                               File "/home/guest/.kodi/addons/script.module.requests/lib/requests/packages/urllib3/connectionpool.py", line 835, in _validate_conn
>                                                 conn.connect()
>                                               File "/home/guest/.kodi/addons/script.module.requests/lib/requests/packages/urllib3/connection.py", line 330, in connect
>                                                 cert = self.sock.getpeercert()
>                                               File "/home/guest/.kodi/addons/script.module.requests/lib/requests/packages/urllib3/contrib/pyopenssl.py", line 324, in getpeercert
>                                                 'subjectAltName': get_subj_alt_name(x509)
>                                               File "/home/guest/.kodi/addons/script.module.requests/lib/requests/packages/urllib3/contrib/pyopenssl.py", line 166, in get_subj_alt_name
>                                                 cert = _Certificate(openssl_backend, peer_cert._x509)
>                                             AttributeError: 'X509' object has no attribute '_x509'
>                                             -->End of Python script error report<--
>

**Comment by beenje** [comment]
If you look at this issue https://github.com/kennethreitz/requests/issues/3701, you'll see that the problem is linked to an out-of-date PyOpenSSL.
On which platform are you?
Can you check the version of PyOpenSSL and try to update to at least 0.14?

**Comment by greve** [comment]
Thanks for the pointer!

This is CentOS 7. So indeed PyOpenSSL somewhat too old.

Found a package to update it to 0.15 - now YouTube works.

Unfortunately Zattoo has stopped working with the update.

So I'll check what is going on there.

In any case, this ticket can be closed. Sorry for the noise.

**Comment by beenje** [comment]
Thanks for the feedback!
