### ISSUE TITLE
Update to latest (or 2.17.1)

### ISSUE THREAD

**Issue by micahg** [Freso/script.module.requests#16]
Hi,

I'm trying to update script.module.dropbox to the dropbox 2 sdk and I think I'm running into this: https://github.com/dropbox/dropbox-sdk-python/issues/106.

According to that report, an update to requests 2.17.1 will resolve the issue. Any chance of an update coming?

I realize this is super vague, but if I delete the module then kodi falls back to my pip installed version (2.18.4) and everything works fine -- I can authorise with dropbox.

**Comment by beenje** [comment]
I just synchronized to 2.18.4 and noticed that urllib3, idna and chardet are not longer distributed with requests. They need to be installed as dependencies. That means new modules to be created for Kodi. I'll look into it but it's gonna take a bit more time.

**Comment by micahg** [comment]
OK, thanks for digging in.

**Comment by beenje** [comment]
I submitted a PR: https://github.com/xbmc/repo-scripts/pull/646

**Comment by beenje** [comment]
PR merged. requests updated to 2.18.4.
