### ISSUE TITLE
kills plex for kodi addon connection to plex server

### ISSUE THREAD

**Issue by avenantsoftware** [Freso/script.module.requests#17]
this latest update kills the plex for kodi addon, it is unable to connect to the plex server, have to revert to version 2.12.4, and disable automatic addon updates in kodi,  if you want the plex for kodi addon to work again...

**Comment by beenje** [comment]
I can't do anything about the plex for kodi add-on.
You should create an issue there instead: https://github.com/plexinc/plex-for-kodi/issues
