### ISSUE TITLE
Kodi 17.5 iOS 2.18.4 failing for YouTube addon 

### ISSUE THREAD

**Issue by darrenslee1** [Freso/script.module.requests#19]
00:56:35.823 T:6142308352   DEBUG: CGUIMediaWindow::GetDirectory (plugin://plugin.video.youtube/)
00:56:35.823 T:6142308352   DEBUG:   ParentPath = [plugin://plugin.video.youtube/]
00:56:35.823 T:6145175552   DEBUG: StartScript - calling plugin YouTube('plugin://plugin.video.youtube/','1','')
00:56:35.823 T:6140588032   DEBUG: Thread LanguageInvoker start, auto delete: false
00:56:35.823 T:6140588032    INFO: initializing python engine.
00:56:35.823 T:6140588032   DEBUG: CPythonInvoker(5, /var/mobile/Library/Preferences/Kodi/addons/plugin.video.youtube/resources/lib/default.py): start processing
00:56:35.831 T:6150336512   DEBUG: CAddonDatabase::SetLastUsed[plugin.video.youtube] took 8 ms
00:56:35.831 T:6141161472   DEBUG: Thread JobWorker start, auto delete: true
00:56:35.846 T:6140588032   DEBUG: -->Python Interpreter Initialized<--
00:56:35.846 T:6140588032   DEBUG: CPythonInvoker(5, /var/mobile/Library/Preferences/Kodi/addons/plugin.video.youtube/resources/lib/default.py): the source file to load is "/var/mobile/Library/Preferences/Kodi/addons/plugin.video.youtube/resources/lib/default.py"
00:56:35.846 T:6140588032   DEBUG: CPythonInvoker(5, /var/mobile/Library/Preferences/Kodi/addons/plugin.video.youtube/resources/lib/default.py): setting the Python path to /var/mobile/Library/Preferences/Kodi/addons/plugin.video.youtube/resources/lib:/var/mobile/Library/Preferences/Kodi/addons/script.module.certifi/lib:/var/mobile/Library/Preferences/Kodi/addons/script.module.chardet/lib:/var/mobile/Library/Preferences/Kodi/addons/script.module.idna/lib:/var/mobile/Library/Preferences/Kodi/addons/script.module.requests/lib:/var/mobile/Library/Preferences/Kodi/addons/script.module.urllib3/lib:/Applications/Kodi.app/Frameworks/lib/python2.7/site-packages/setuptools-18.4-py2.7.egg:/Applications/Kodi.app/Frameworks/lib/python2.7/site-packages/Pillow-3.0.0-py2.7-macosx-10.4-x86_64.egg:/Applications/Kodi.app/Frameworks:/Applications/Kodi.app/Frameworks/lib/python27.zip:/Applications/Kodi.app/Frameworks/lib/python2.7:/Applications/Kodi.app/Frameworks/lib/python2.7/plat-darwin:/Applications/Kodi.app/Frameworks/lib/python2.7/plat-mac:/Applications/Kodi.app/Frameworks/lib/python2.7/plat-mac/lib-scriptpackages:/Applications/Kodi.app/Frameworks/lib/python2.7/lib-tk:/Applications/Kodi.app/Frameworks/lib/python2.7/lib-old:/Applications/Kodi.app/Frameworks/lib/python2.7/lib-dynload:/Applications/Kodi.app/Frameworks/lib/python2.7/site-packages
00:56:35.846 T:6140588032   DEBUG: CPythonInvoker(5, /var/mobile/Library/Preferences/Kodi/addons/plugin.video.youtube/resources/lib/default.py): entering source directory /var/mobile/Library/Preferences/Kodi/addons/plugin.video.youtube/resources/lib
00:56:35.846 T:6140588032   DEBUG: CPythonInvoker(5, /var/mobile/Library/Preferences/Kodi/addons/plugin.video.youtube/resources/lib/default.py): instantiating addon using automatically obtained id of "plugin.video.youtube" dependent on version 2.19.0 of the xbmc.python api
00:56:36.156 T:6140588032   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.IOError'>
                                            Error Contents: (10, 'No child processes')
                                            Traceback (most recent call last):
                                              File "/var/mobile/Library/Preferences/Kodi/addons/plugin.video.youtube/resources/lib/default.py", line 3, in <module>
                                                from youtube_plugin.kodion import runner
                                              File "/var/mobile/Library/Preferences/Kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/kodion/__init__.py", line 17, in <module>
                                                from requests import api as client
                                              File "/var/mobile/Library/Preferences/Kodi/addons/script.module.requests/lib/requests/__init__.py", line 97, in <module>
                                                from . import utils
                                              File "/var/mobile/Library/Preferences/Kodi/addons/script.module.requests/lib/requests/utils.py", line 42, in <module>
                                                if platform.system() == 'Windows':
                                              File "/Users/Shared/jenkins/workspace/IOS-ARM64/tools/depends/xbmc-depends/iphoneos8.1_arm64-target/lib/python2.7/platform.py", line 1263, in system
                                              File "/Users/Shared/jenkins/workspace/IOS-ARM64/tools/depends/xbmc-depends/iphoneos8.1_arm64-target/lib/python2.7/platform.py", line 1230, in uname
                                              File "/Users/Shared/jenkins/workspace/IOS-ARM64/tools/depends/xbmc-depends/iphoneos8.1_arm64-target/lib/python2.7/platform.py", line 965, in _syscmd_uname
                                            IOError: (10, 'No child processes')
                                            -->End of Python script error report<--
00:56:36.162 T:6140588032    INFO: Python script stopped
00:56:36.162 T:6140588032   DEBUG: Thread LanguageInvoker 6140588032 terminating
00:56:36.168 T:6142308352   ERROR: GetDirectory - Error getting plugin://plugin.video.youtube/
00:56:36.168 T:6142308352   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.youtube/) failed
00:56:36.169 T:6142308352   DEBUG: CGUIMediaWindow::GetDirectory ()
00:56:36.169 T:6142308352   DEBUG:   ParentPath = [plugin://plugin.video.youtube/]
00:56:36.171 T:6140588032   DEBUG: Thread BackgroundLoader start, auto delete: false
00:56:36.173 T:6140588032   DEBUG: Thread BackgroundLoader 6140588032 terminating
00:56:36.174 T:6140588032   DEBUG: Thread BackgroundLoader start, auto delete: false
00:56:36.176 T:6140588032   DEBUG: Thread BackgroundLoader 6140588032 terminating

**Comment by darrenslee1** [comment]
Downgraded works with 2.18.2

**Comment by beenje** [comment]
The issue is linked to the call to `platform.system()` in requests/utils.py

I saw that this was recently changed to `sys.platform` on master: https://github.com/requests/requests/commit/a05aac7007dd802401d59b6380ef95095836ed9b

Do you have any way of testing if this would work on iOS?

**Comment by darrenslee1** [comment]
:-( no promises since I'm a newbie to this scene. I can try to pull from requests/requests@a05aac7 - figure out a way to sideload request/utils.py

Let me try tonight and report back if I can/can't.
Thanks!

**Comment by darrenslee1** [comment]
No code ninja skills on my end: still a n00b...

00:40:51.193 T:6151270400   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.TypeError'>
                                            Error Contents: 'str' object is not callable
                                            Traceback (most recent call last):
                                              File "/var/mobile/Library/Preferences/Kodi/addons/plugin.video.youtube/resources/lib/startup.py", line 3, in <module>
                                                from youtube_plugin.kodion.impl import Context
                                              File "/var/mobile/Library/Preferences/Kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/kodion/__init__.py", line 17, in <module>
                                                from requests import api as client
                                              File "/var/mobile/Library/Preferences/Kodi/addons/script.module.requests/lib/requests/__init__.py", line 97, in <module>
                                                from . import utils
                                              File "/var/mobile/Library/Preferences/Kodi/addons/script.module.requests/lib/requests/utils.py", line 42, in <module>
                                                if sys.platform == 'win32':
                                            TypeError: 'str' object is not callable
                                            -->End of Python script error report<--
00:40:51.199 T:6151270400    INFO: Python script stopped

**Comment by darrenslee1** [comment]
Googling and this... https://github.com/Rip-Rip/clang_complete/issues/282

**Comment by beenje** [comment]
I don't get where the TypeError exception comes from in your test...
Could you paste somewhere (pastebin.com for example) the full requests/utils.py file you used?

Anyway, the link you mentioned is interesting.
On iOS, Python is compiled with Kodi. The initial error might be linked to some compilation issue.
Could you ask on https://forum.kodi.tv why an exception is raised when calling platform.system() on iOS?

**Comment by darrenslee1** [comment]
if 'win32' in sys.platform:

This works. Borrowed coding from https://github.com/analogue/mythbox/blob/master/resources/src/mythbox/platform.py#L31

**Comment by darrenslee1** [comment]
I suck at github. I just made local changes at my iOS locally. Someone want to test at Windows and merge?

**Comment by darrenslee1** [comment]
Actually sys.platform == 'win32' works... my iOS editor has an issue with \n new lines. I updated in the code inline without new lines and that works. Odd... as I said, I'm a Kodi n00b.

**Comment by beenje** [comment]
That's good news.
Thanks for the tests! Everyone has to start somewhere. You learn by trying!

I'll wait for the next version of requests (that will include this change).
I'll also try to ask in Kodi forum why `platform.system()` crashes on iOS. That shouldn't be the case.

**Comment by beenje** [comment]
The next version of requests took a while but was published in June: https://github.com/requests/requests/releases

Someone just made a PR to update to 2.19.1.
I'll send a PR to the official add-on repository. That will fix your issue.
