### ISSUE TITLE
[Feature request] Include the requests[socks] library

### ISSUE THREAD

**Issue by dagwieers** [Freso/script.module.requests#23]
Would it be possible to include the **requests[socks]** library as part of this package ?

The main reason for this is that the myriad of addons that use the **requests** library do not support Kodi's proxy settings. I am trying to change this by patching various common Kodi addons, but since the global Kodi settings include both HTTP and SOCKS support it does require the **requests[socks]** library as well.

Cfr. https://github.com/pietje666/plugin.video.vrt.nu/pull/87 and https://github.com/emilsvennesson/script.module.inputstreamhelper/pull/51

**Comment by beenje** [comment]
From https://github.com/kennethreitz/requests/blob/a345b776fb2cf67d1a1810349e71fd60a83f53eb/setup.py#L104

```
extras_require={
        'security': ['pyOpenSSL >= 0.14', 'cryptography>=1.3.4', 'idna>=2.0.0'],
        'socks': ['PySocks>=1.5.6, !=1.5.7'],
        'socks:sys_platform == "win32" and python_version == "2.7"': ['win_inet_pton'],
    },
```

requests[socks] just specifies to install PySocks library as well as requests (and win_inet_pton on win32).
To use socks with requests in Kodi, you'd need to submit PySocks as a new add-on.
It doesn't belong in requests itself.

**Comment by dagwieers** [comment]
@beenje Thanks for feedback, I'll be looking into this. Kind regards.

**Comment by dagwieers** [comment]
New [script.module.pysocks](https://github.com/dagwieers/script.module.pysocks) module proposed to default Kodi repo at https://github.com/xbmc/repo-scripts/pull/1025
