### ISSUE TITLE
Conflicts between requests and os random

### ISSUE THREAD

**Issue by iparr** [Freso/script.module.requests#8]
Please see this issue: https://github.com/vonH/plugin.video.iplayerwww/issues/22

It seems that requests is having some conflicts with `osrandom` (or vis-versa?)

Can someone give me any pointers on fixing this?

**Comment by beenje** [comment]
See https://github.com/pyca/cryptography/issues/2287
Installing cryptography 1.1 from pip seems to fix the problem.
Can you confirm?

**Comment by iparr** [comment]
The plugin I was having problems with now starts okay.
Thank you for your help.
For reference, `pip install cryptography --upgrade` fixed this.

**Comment by beenje** [comment]
Thanks for reporting back.
